name: ci

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, closed]

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      API_URL: http://localhost:3333

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm test
      - run: pnpm check-types
      - run: pnpm check-styles
      - run: pnpm lint --fix
      - run: pnpm build
